import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex">
        <div className="w-1/2 h-[600px] overflow-hidden rounded-2xl">
          <Image
            src="/bg-orbs.png"
            alt="yellow and green orbs"
            width={800}
            height={800}
            className="blur-3xl opacity-70"
          />
        </div>
        <div className="relative w-1/3 rounded-2xl overflow-hidden">
          <Image
            src="/portrait.jpg"
            fill
            className="rounded-2xl object-cover"
          />
        </div>
      </main>
    </div>
  );
}
