import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/navbar";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="flex">
        <div className="w-2/3 h-[600px] mx-5 relative overflow-hidden rounded-2xl">
          <Image
            src="/bg-orbs.png"
            alt="yellow and green orbs"
            width={2000}
            height={2000}
            className="blur-3xl opacity-70"
          />
          <div className="w-3/4 absolute top-0 p-12 ">
            <h1 className="text-5xl tracking-tight">
              Hey, I'm Eliane, a web developer
            </h1>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Risus
              ultricies tristique nulla aliquet. Congue mauris rhoncus aenean
              vel elit scelerisque mauris pellentesque. Egestas pretium aenean
              pharetra magna ac placerat vestibulum lectus.
            </p>
            <button className="py-3 px-6 text-white bg-black rounded-full">
              Contact me
            </button>
            <button className="p-3 bg-neutral-50 rounded-full">Gith</button>
            <button className="p-3 bg-neutral-50 rounded-full">Linked</button>
          </div>
        </div>
        <div className="relative w-1/3 mr-5 rounded-2xl overflow-hidden">
          <Image
            src="/portrait.jpg"
            fill
            className="rounded-2xl object-cover"
          />
        </div>
      </main>
    </div>
  );
}
